matrix:
  allow_failures:
    - env: GHCVER=head

env:
 - GHCVER=7.8.3
 - GHCVER=7.10.1
 - GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.20 update
 - travis_retry cabal-1.20 install Cabal
 - travis_retry cabal-1.20 install alex happy
 - travis_retry cabal-1.20 install gtk2hs-buildtools

script:
 - cabal-1.20 install

notifications:
  irc: "chat.freenode.net#yi"
